platform :ios, '7.0'
target 'GIOSdkIosDemo’ do

pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'

#使用 CocoaPods 快速集成GrowingIO SDK

pod 'GrowingIO'

end
